### ISSUE TITLE
Scaffold is broken

### ISSUE THREAD

**Issue by runemadsen** [designsystemsinternational/clis#43]
After the SSR changes, I'm now getting the following error on a vanilla repo when running `npm run dev`:

```
Html Webpack Plugin:
  Error: Child compilation failed:
  Entry module not found: Error: Can't resolve '/Users/runemadsen/Projects/superbright/superbright-scroll-test/src/index.html' in '/Use  rs/runemadsen/Projects/superbright/superbright-scroll-test'
```

@bravomartin Can you take a look? Let's remember to test the PR's a bit better, since both `scaffold` and `static` was broken for me after the PR.

**Comment by runemadsen** [comment]
Looking at the code, it's still expecting `index.html` to be there on client render, but even though I add this file, I get a mismatch from React since the tags are all different. It seems like `npm run dev` has not ben changed to fit with the new SSR.

**Comment by bravomartin** [comment]
After a long circle I came back to the beginning. I did test the template and worked fine whenever I ran it from inside the template folder.

The issue was that `index.html` was in the ignore list (before this PR), so it was never copied. After that single change everything works as expected. I actually don't understand how it worked before. Since index.html is indeed required for the `html-webpack-plugin` to work.

Tested in the template and also ran the cli, and the test project works fine. See this pr:

https://github.com/designsystemsinternational/clis/pull/44

**Comment by bravomartin** [comment]
also can you explain how static was broken after the pr?

**Comment by runemadsen** [comment]
Sounds good! I pasted the error message above, so that's what was broken.

**Comment by bravomartin** [comment]
The error is for scaffold. You also mention an error on static?

**Comment by runemadsen** [comment]
Ah ok. I already fixed the static error in [this PR](https://github.com/designsystemsinternational/clis/pull/42)

**Comment by bravomartin** [comment]
Oops
-- 
MB
https://designsystems.international
